<a href="https://colab.research.google.com/github/gumpinan-byte/IIA-DeptActivity-25ME1A4249/blob/main/week-1/Agriculture49.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
crop_data  = {
    "crop_name": "Rice",
    "scientific_name": "Oryza sativa",
    "crop_type": "Cereal",
    "season": "Kharif",
    "ideal_temperature_celsius": 25,
    "annual_rainfall_mm": 1200,
    "soil_type": "Clayey Loam",
    "ideal_Soil_ph": 6.5,
    "growing_duration_days":120,
    "water_requirements":"High",
    "average_yield_per_hectare_kg":4000,
    "primary_nutrients":["Nitrogen","Phosphorus","Potassius"],
    "common_pests":["stem Borer","Brown Planthopper"],
    "harvesting_method":"Manual/Mechanical",
    "storage_humidity_percent":13
}
print(crop_data)
crop_data["Area"]="Eluru"
crop_data["Pesticide"]="Urea"
crop_data["primary_nutrients"] =["Calcium", "Magnesium", "Sulphur"]
crop_data["common_pests"]=["Fall Armyworm"]
print(crop_data)

{'crop_name': 'Rice', 'scientific_name': 'Oryza sativa', 'crop_type': 'Cereal', 'season': 'Kharif', 'ideal_temperature_celsius': 25, 'annual_rainfall_mm': 1200, 'soil_type': 'Clayey Loam', 'ideal_Soil_ph': 6.5, 'growing_duration_days': 120, 'water_requirements': 'High', 'average_yield_per_hectare_kg': 4000, 'primary_nutrients': ['Nitrogen', 'Phosphorus', 'Potassius'], 'common_pests': ['stem Borer', 'Brown Planthopper'], 'harvesting_method': 'Manual/Mechanical', 'storage_humidity_percent': 13}
{'crop_name': 'Rice', 'scientific_name': 'Oryza sativa', 'crop_type': 'Cereal', 'season': 'Kharif', 'ideal_temperature_celsius': 25, 'annual_rainfall_mm': 1200, 'soil_type': 'Clayey Loam', 'ideal_Soil_ph': 6.5, 'growing_duration_days': 120, 'water_requirements': 'High', 'average_yield_per_hectare_kg': 4000, 'primary_nutrients': ['Calcium', 'Magnesium', 'Sulphur'], 'common_pests': ['Fall Armyworm'], 'harvesting_method': 'Manual/Mechanical', 'storage_humidity_percent': 13, 'Area': 'Eluru', 'Pesticide': 'Urea'}

In [ ]:
import pandas as pd

# Convert the single dictionary to a DataFrame by wrapping it in a list
df = pd.DataFrame([crop_data])

# Save the DataFrame to a CSV file
df.to_csv('crop_data.csv', index=False)

# Display the DataFrame to verify
display(df)

,crop_name,scientific_name,crop_type,season,ideal_temperature_celsius,annual_rainfall_mm,soil_type,ideal_Soil_ph,growing_duration_days,water_requirements,average_yield_per_hectare_kg,primary_nutrients,common_pests,harvesting_method,storage_humidity_percent,Area,Pesticide
0,Rice,Oryza sativa,Cereal,Kharif,25,1200,Clayey Loam,6.5,120,High,4000,"[Calcium, Magnesium, Sulphur]",[Fall Armyworm],Manual/Mechanical,13,Eluru,Urea

In [ ]:
# Prepare the DataFrame for MS Excel
excel_df = df.copy()

# Clean up any list columns so they display cleanly as text in Excel
for col in excel_df.columns:
    if isinstance(excel_df[col].iloc[0], list):
        excel_df[col] = excel_df[col].apply(lambda x: "; ".join(x))

# Save with 'utf-8-sig' encoding which MS Excel uses to display special characters correctly
excel_df.to_csv('crop_data_excel.csv', index=False, encoding='utf-8-sig')

# Display the cleaned DataFrame
display(excel_df)

,crop_name,scientific_name,crop_type,season,ideal_temperature_celsius,annual_rainfall_mm,soil_type,ideal_Soil_ph,growing_duration_days,water_requirements,average_yield_per_hectare_kg,primary_nutrients,common_pests,harvesting_method,storage_humidity_percent,Area,Pesticide
0,Rice,Oryza sativa,Cereal,Kharif,25,1200,Clayey Loam,6.5,120,High,4000,Calcium; Magnesium; Sulphur,Fall Armyworm,Manual/Mechanical,13,Eluru,Urea

In [ ]:
from google.colab import files

# Download the Excel-optimized CSV file directly to your local system
files.download('crop_data_excel.csv')

In [ ]:
# Prepare the DataFrame for Google Sheets
google_sheets_df = df.copy()

# Convert list columns to clean, comma-separated strings for Google Sheets
for col in google_sheets_df.columns:
    if isinstance(google_sheets_df[col].iloc[0], list):
        google_sheets_df[col] = google_sheets_df[col].apply(lambda x: ", ".join(x))

# Save with standard UTF-8 encoding (ideal for Google Sheets upload)
google_sheets_df.to_csv('crop_data_sheets.csv', index=False, encoding='utf-8')

# Download the file to your computer
from google.colab import files
files.download('crop_data_sheets.csv')

# Display preview
display(google_sheets_df)

,crop_name,scientific_name,crop_type,season,ideal_temperature_celsius,annual_rainfall_mm,soil_type,ideal_Soil_ph,growing_duration_days,water_requirements,average_yield_per_hectare_kg,primary_nutrients,common_pests,harvesting_method,storage_humidity_percent,Area,Pesticide
0,Rice,Oryza sativa,Cereal,Kharif,25,1200,Clayey Loam,6.5,120,High,4000,"Calcium, Magnesium, Sulphur",Fall Armyworm,Manual/Mechanical,13,Eluru,Urea